### ISSUE TITLE
where's the code?

### ISSUE THREAD

**Issue by tve** [TotallyInformation/node-red-contrib-infocache#1]
Dunno whether I've lost all my marbles or what, but I don't see any code in this repo?

**Comment by TotallyInformation** [comment]
No, you haven't lost anything, not even the code!

Sorry, I've been tied up with my day-job and family matters so this has had to take a back-burner for a while.

In the meantime, there is an easy workaround. Please see the uibuilder WIKI for details, I've written some code that goes into a function node and does the simple basics of what this will end up doing.

**Comment by TotallyInformation** [comment]
Code is starting to appear :)
